# Generated by Django 3.1.3 on 2021-03-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210313_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='userId',
            field=models.IntegerField(default=0),
        ),
    ]
